version: '3.8'
services:
  lookup:
    container_name: lookup
    image: madflojo/tarmac:unstable
    ports:
      - 80:8080
    healthcheck: 
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      - "APP_ENABLE_TLS=false"
      - "APP_LISTEN_ADDR=0.0.0.0:8080"
      - "APP_DEBUG=false"
      - "APP_TRACE=false"
      - "APP_WASM_FUNCTION_CONFIG=/config/tarmac-basic.json"
      - "APP_ENABLE_SQL=true"
      - "APP_SQL_TYPE=mysql"
      - "APP_SQL_DSN=root:example@tcp(mysql:3306)/example"
      - "APP_ENABLE_KVSTORE=true"
      - "APP_KVSTORE_TYPE=redis"
      - "APP_REDIS_SERVER=redis:6379"
    volumes:
      - "./config:/config"
      - "./functions/build:/functions"
    depends_on:
      - mysql
      - redis
      - grafana

  data-manager:
    container_name: data-manager
    image: madflojo/tarmac:unstable
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      - "APP_ENABLE_TLS=false"
      - "APP_LISTEN_ADDR=0.0.0.0:8080"
      - "APP_DEBUG=false"
      - "APP_TRACE=false"
      - "APP_WASM_FUNCTION_CONFIG=/config/tarmac.json"
      - "APP_ENABLE_SQL=true"
      - "APP_SQL_TYPE=mysql"
      - "APP_SQL_DSN=root:example@tcp(mysql:3306)/example"
      - "APP_ENABLE_KVSTORE=true"
      - "APP_KVSTORE_TYPE=redis"
      - "APP_REDIS_SERVER=redis:6379"
    volumes:
      - "./config:/config"
      - "./functions/build:/functions"
    depends_on:
      - mysql
      - redis
      - grafana


  # Dependencies
  mysql:
    image: bitnami/mysql:latest
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: example
    ports:
      - 3306:3306
  redis:
    image: bitnami/redis:latest
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/config/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./config:/config
      - prom_data:/prometheus
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=example
    volumes:
      - ./config/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./config/grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./config/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
  k6-stress:
    image: grafana/k6
    container_name: k6
    volumes:
      - ./tests:/tests
    command: run --config /tests/k6/stress.json /tests/k6/script.js
    depends_on:
      - lookup
      - data-manager
  k6-soak:
    image: grafana/k6
    container_name: k6
    volumes:
      - ./tests:/tests
    command: run --config /tests/k6/soak.json /tests/k6/script.js
    depends_on:
      - lookup
      - data-manager


    
volumes:
  prom_data:
