version: '3.8'
services:
  airport-lookup-example:
    image: tarmac:local
    ports:
      - 80:8080
    environment:
      - "APP_ENABLE_TLS=false"
      - "APP_LISTEN_ADDR=0.0.0.0:8080"
      - "APP_DEBUG=true"
      - "APP_TRACE=true"
      - "APP_WASM_FUNCTION_CONFIG=/config/tarmac.json"
    volumes:
      - "./config:/config"
      - "./functions/build:/functions"
