name: load

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
jobs:
  load-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run the Service
      run: make run
    - name: Wait for the Service to be ready
      run: |
        while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost/ready)" != "200" ]]; do sleep 5; done
    - name: Configure Test
      run: |
        cat << EOF > loadtest-config.yml
          url: http://localhost:8080
          SLOs:
            http/error-rate: 0
            http/latency-p99.9: 5
        EOF
    - uses: iter8-tools/iter8-action@v1
      with:
        chart: load-test-http
        valuesFile: loadtest-config.yml 
