name: load

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
jobs:
  load-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run the Service
      run: make run-background
    - name: Wait for the Service to be ready
      run: |
        while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:8080/ready)" != "200" ]]; do sleep 5; done
    - name: Run the load tests
      run: make run-stress
