name: load

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
jobs:
  load-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Data Manager
      run: |
        make build loadtest-setup
    - name: Wait for the Service to be ready
      run: |
        while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:8080/ready)" != "200" ]]; do sleep 5; done
