name: load

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
jobs:
  load-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run the data-manager
      run: make run-background
    - name: Wait for the data-manager to start
      run: while ! curl -s http://localhost:8080/ready; do sleep 1; done
    - name: Run the load tests
      run: make run-stress
